exclude_paths:
- "font_end/portfolio_redux_front/"

engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      no-multi-spaces:
        enabled: false
  csslint:
    enabled: true
  fixme:
    enabled: false
