# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bca75fa884da543672354b38ccf5caf7b8bad9f252738861503c2188f67b3a48a5096bb9518e392023426aabda2938c72019990c1ab4680fad8a31cea9cc2905

test:
  secret_key_base: 9a150626b1084274c39a08f17f2eb02af3be5dd4498e798bacdd05c64cde631402c11b17462055d2c7f4bd9261f6cf34b206764223a0bfc949d6acc6cd7b467f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
