default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_rails_development

test:
  <<: *default
  database: portfolio_rails_test

production:
  <<: *default
  database: portfolio_rails_production
  username: portfolio_rails
  password: <%= ENV['PORTFOLIO_RAILS_DATABASE_PASSWORD'] %>
